[package]
name = "feather-lrgen"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
feather-parse = { path = "../feather-parse" }
quote = "1.0"
