[package]
name = "feather-ast"
version = "0.0.1"
edition = "2021"
license = "LGPL-3.0-only"

[lib]
name = "featherast"
crate-type = ["rlib"]

[dependencies]
lazy_static = "1.4"
regex = "1.10"
serde_json = "1.0"
serde = { version = "1.0.196", features = ["derive"] }
