[package]
name = "feather-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "feather-cli"

[dependencies]
feather-ast = { path = "../feather-ast" }
feather-parse = { path = "../feather-parse" }
exitcode = "1.1"
serde_json = "1.0"
structopt = "0.3"
