[package]
name = "feather-cli"
version = "0.0.1"
edition = "2021"
license = "LGPL-3.0-only"

[[bin]]
name = "feather-cli"

[dependencies]
feather-ast = { path = "../feather-ast" }

exitcode = "1.1"
serde_json = "1.0"
structopt = "0.3"
